apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - imagePullPolicy: Never
        image: mysql_img
        name: mysql
        livenessProbe:
          exec:
            command:
            - sh
            - healthy.sh
          initialDelaySeconds: 30
          periodSeconds: 30
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: mysql
      volumes:
        - name: mysql
          persistentVolumeClaim:
            claimName: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi    
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: mysql
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  type: ClusterIP
  clusterIP: 10.110.209.122